language: node_js
node_js:
  - "0.12"

before_script:
  - npm install mocha
  - npm install -g istanbul
  - npm install coveralls
  - npm install mockery

env:
  - TEST_DIR=hot-sauce
  - TEST_DIR=ajwain
  - TEST_DIR=salt-pepper
  - TEST_DIR=chives

script:
  - cd $TEST_DIR && npm install && npm run coveralls